# Generated by Django 3.2.25 on 2025-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('count_grate', models.IntegerField()),
            ],
            options={
                'db_table': 'five',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearAirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('max_PM', models.FloatField()),
                ('min_PM10', models.FloatField()),
            ],
            options={
                'db_table': 'four',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoCategory',
            fields=[
                ('Co_category', models.CharField(max_length=50, verbose_name='CO分类')),
                ('Co_count', models.IntegerField(verbose_name='数量')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'seven',
            },
        ),
        migrations.CreateModel(
            name='O3Category',
            fields=[
                ('O3_category', models.CharField(max_length=50, verbose_name='O3分类')),
                ('O3_count', models.IntegerField(verbose_name='数量')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'eight',
            },
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('date', models.DateField(verbose_name='日期')),
                ('airQuality', models.CharField(max_length=50, verbose_name='质量等级')),
                ('AQI', models.IntegerField(verbose_name='AQI')),
                ('rank', models.IntegerField(verbose_name='当日排名')),
                ('PM', models.FloatField(verbose_name='PM2.5')),
                ('PM10', models.FloatField(verbose_name='PM10')),
                ('So2', models.FloatField(verbose_name='So2')),
                ('No2', models.FloatField(verbose_name='No2')),
                ('Co', models.FloatField(verbose_name='Co')),
                ('O3', models.FloatField(verbose_name='O3')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'airdata',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('creteTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
