# Generated by Django 3.2.25 on 2025-07-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airquality',
            options={},
        ),
        migrations.AlterModelOptions(
            name='yearairquality',
            options={},
        ),
    ]
